version: 2.1

jobs:
  pythonTests:
    executor: python-build
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Generate cache seeds"
          command: find . -name Pipfile.lock | sort | xargs md5sum > /tmp/checksums
      - restore_cache:
          key: deps-2-{{ checksum "/tmp/checksums" }}
      - run:
          command: pwd && ls
      - run:
          name: "Install deps"
          command: pip3 --no-cache install pipenv && pipenv install --dev --deploy
      - save_cache:
          key: deps-2-{{ checksum "/tmp/checksums" }}
          paths:
            - "/root/.local/share/virtualenvs"
      - run:
          name: "PyTest"
          command: |
            PYTHONPATH=. pipenv run coverage run --source . -m pytest
            PYTHONPATH=. pipenv run coverage report
            PYTHONPATH=. pipenv run coverage html
      - store_test_results:
          path: test-reports
          prefix: tests
      - store_artifacts:
          path: htmlcov

  runHooks:
    executor: python-build
    steps:
      - checkout
      - run:
          name: "Install pre-commit"
          command: pip install pre-commit --user
      - run: pre-commit run -a -c .pre-commit-config.ci.yaml

  mypy:
    executor: python-build
    steps:
      - checkout
      - run:
          name: "Generate cache seeds"
          command: find . -name Pipfile.lock | sort | xargs md5sum > /tmp/checksums
      - restore_cache:
          key: deps-2-{{ checksum "/tmp/checksums" }}
      - run:
          name: "Install deps"
          command: pip3 --no-cache install pipenv && pipenv install --dev --deploy
      - save_cache:
          key: deps-2-{{ checksum "/tmp/checksums" }}
          paths:
            - "/root/.local/share/virtualenvs"
      - run:
          name: "mypy"
          command: pipenv run mypy bento
      - store_test_results:
          path: test-reports
          prefix: tests
      - store_artifacts:
          path: test-reports

  runAcceptance:
    executor: python-build
    steps:
      - checkout
      - run:
          name: "Generate cache seeds"
          command: find . -name Pipfile.lock | sort | xargs md5sum > /tmp/checksums
      - restore_cache:
          key: deps-2-{{ checksum "/tmp/checksums" }}
      - run:
          name: "Install deps"
          command: pip3 --no-cache install pipenv && pipenv install --dev --deploy
      - save_cache:
          key: deps-2-{{ checksum "/tmp/checksums" }}
          paths:
            - "/root/.local/share/virtualenvs"
      - run:
          name: "QA Tests"
          command: make qa-test

  envAcceptance:
    executor: python-build
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Python 3.6 Tests"
          command: make env-test

  bentoRun:
    working_directory: ~/circleci
    executor: python-build
    steps:
      - checkout
      - run:
          name: "Configure pipenv"
          command: pipenv install --dev
      - run:
          name: "Make bento"
          command: pipenv run make -B build && pipenv run bento --version --agree
      - run:
          name: "Install react"
          command: (cd tests/integration/react && npm install)
      - run:
          name: "Running bento check"
          command: pipenv run bento --agree --email test@returntocorp.com check --no-pager

workflows:
  build-and-deploy:
    jobs:
      - pythonTests
      - runHooks
      - mypy
      - runAcceptance
      - envAcceptance
      - bentoRun

executors:
  python-build:
    working_directory: ~/circleci
    docker:
      - image: circleci/python:3.7.4-stretch-node
